### ISSUE TITLE
Adding to AuxClasspath - wrong behaviour

### ISSUE THREAD

**Issue by aamotharald** [gleclaire/findbugs-maven-plugin#48] opened 2016-11-23 08:22 UTC
Hi All,

I have an OSGi Project that also pulls a dependency jar with Maven.

When I run a maven findbugs:findbugs on the project, I get the debug Message:
     [java] The following errors occurred during analysis:
     [java]   File not found: filesystem:%MyProjectDir%\lib\commons-net.jar%MyProjectDir%\lib\commons-net.jar

The debug of the run reveals:
[DEBUG]   Adding to AuxClasspath ->%MyProjectDir%\lib\commons-net.jar
[DEBUG]   Adding to AuxClasspath ->%MyProjectDir%\lib\commons-net.jar
[DEBUG]   AuxClasspath is ->%MyHomeDir%\.m2\repository\org\codehaus\mojo\findbugs-maven-plugin\3.0.4\findbugs-maven-plugin-3.0.4.jar;%MyHomeDir%\.m2\repository\com\google\code\findbugs\findbugs\3.0.1\findbugs-3.0.1.jar;%MyHomeDir%\.m2\repository\net\jcip\jcip-annotations\1.0\jcip-annotations-1.0.jar;%MyHomeDir%\.m2\repository\com\google\code\findbugs\jsr305\2.0.1\jsr305-2.0.1.jar;%MyHomeDir%\.m2\repository\com\google\code\findbugs\bcel-findbugs\6.0\bcel-findbugs-6.0.jar;%MyHomeDir%\.m2\repository\com\google\code\findbugs\jFormatString\2.0.1\jFormatString-2.0.1.jar;%MyHomeDir%\.m2\repository\dom4j\dom4j\1.6.1\dom4j-1.6.1.jar;%MyHomeDir%\.m2\repository\xml-apis\xml-apis\1.0.b2\xml-apis-1.0.b2.jar;%MyHomeDir%\.m2\repository\org\ow2\asm\asm-debug-all\5.0.2\asm-debug-all-5.0.2.jar;%MyHomeDir%\.m2\repository\org\ow2\asm\asm-commons\5.0.2\asm-commons-5.0.2.jar;%MyHomeDir%\.m2\repository\org\ow2\asm\asm-tree\5.0.2\asm-tree-5.0.2.jar;%MyHomeDir%\.m2\repository\org\ow2\asm\asm\5.0.2\asm-5.0.2.jar;%MyHomeDir%\.m2\repository\commons-lang\commons-lang\2.6\commons-lang-2.6.jar;%MyHomeDir%\.m2\repository\com\apple\AppleJavaExtensions\1.4\AppleJavaExtensions-1.4.jar;%MyHomeDir%\.m2\repository\jaxen\jaxen\1.1.6\jaxen-1.1.6.jar;%MyHomeDir%\.m2\repository\org\apache\ant\ant\1.9.4\ant-1.9.4.jar;%MyHomeDir%\.m2\repository\org\apache\ant\ant-launcher\1.9.4\ant-launcher-1.9.4.jar;%MyHomeDir%\.m2\repository\org\codehaus\groovy\groovy\2.4.7\groovy-2.4.7.jar;%MyHomeDir%\.m2\repository\org\codehaus\groovy\groovy-ant\2.4.7\groovy-ant-2.4.7.jar;%MyHomeDir%\.m2\repository\org\apache\ant\ant-antlr\1.9.4\ant-antlr-1.9.4.jar;%MyHomeDir%\.m2\repository\org\codehaus\groovy\groovy-groovydoc\2.4.7\groovy-groovydoc-2.4.7.jar;%MyHomeDir%\.m2\repository\org\codehaus\groovy\groovy-templates\2.4.7\groovy-templates-2.4.7.jar;%MyHomeDir%\.m2\repository\org\apache\ant\ant-junit\1.9.4\ant-junit-1.9.4.jar;%MyHomeDir%\.m2\repository\org\codehaus\groovy\groovy-xml\2.4.7\groovy-xml-2.4.7.jar;%MyHomeDir%\.m2\repository\org\apache\maven\reporting\maven-reporting-impl\2.1\maven-reporting-impl-2.1.jar;%MyHomeDir%\.m2\repository\org\apache\maven\maven-project\2.0.10\maven-project-2.0.10.jar;%MyHomeDir%\.m2\repository\org\apache\maven\maven-settings\2.0.10\maven-settings-2.0.10.jar;%MyHomeDir%\.m2\repository\org\apache\maven\maven-profile\2.0.10\maven-profile-2.0.10.jar;%MyHomeDir%\.m2\repository\org\apache\maven\maven-plugin-registry\2.0.10\maven-plugin-registry-2.0.10.jar;%MyHomeDir%\.m2\repository\org\codehaus\plexus\plexus-interpolation\1.1\plexus-interpolation-1.1.jar;%MyHomeDir%\.m2\repository\commons-validator\commons-validator\1.2.0\commons-validator-1.2.0.jar;%MyHomeDir%\.m2\repository\commons-beanutils\commons-beanutils\1.7.0\commons-beanutils-1.7.0.jar;%MyHomeDir%\.m2\repository\commons-digester\commons-digester\1.6\commons-digester-1.6.jar;%MyHomeDir%\.m2\repository\commons-logging\commons-logging\1.0.4\commons-logging-1.0.4.jar;%MyHomeDir%\.m2\repository\oro\oro\2.0.8\oro-2.0.8.jar;%MyHomeDir%\.m2\repository\org\apache\maven\reporting\maven-reporting-api\3.0\maven-reporting-api-3.0.jar;%MyHomeDir%\.m2\repository\org\apache\maven\maven-plugin-api\2.0\maven-plugin-api-2.0.jar;%MyHomeDir%\.m2\repository\org\apache\maven\maven-plugin-descriptor\2.2.1\maven-plugin-descriptor-2.2.1.jar;%MyHomeDir%\.m2\repository\org\apache\maven\maven-artifact\2.2.1\maven-artifact-2.2.1.jar;%MyHomeDir%\.m2\repository\org\apache\maven\doxia\doxia-core\1.4\doxia-core-1.4.jar;%MyHomeDir%\.m2\repository\org\apache\maven\doxia\doxia-logging-api\1.4\doxia-logging-api-1.4.jar;%MyHomeDir%\.m2\repository\org\codehaus\plexus\plexus-component-annotations\1.5.5\plexus-component-annotations-1.5.5.jar;%MyHomeDir%\.m2\repository\xerces\xercesImpl\2.9.1\xercesImpl-2.9.1.jar;%MyHomeDir%\.m2\repository\org\apache\httpcomponents\httpclient\4.0.2\httpclient-4.0.2.jar;%MyHomeDir%\.m2\repository\commons-codec\commons-codec\1.3\commons-codec-1.3.jar;%MyHomeDir%\.m2\repository\org\apache\httpcomponents\httpcore\4.0.1\httpcore-4.0.1.jar;%MyHomeDir%\.m2\repository\org\apache\maven\doxia\doxia-sink-api\1.4\doxia-sink-api-1.4.jar;%MyHomeDir%\.m2\repository\org\apache\maven\doxia\doxia-decoration-model\1.4\doxia-decoration-model-1.4.jar;%MyHomeDir%\.m2\repository\org\apache\maven\doxia\doxia-site-renderer\1.4\doxia-site-renderer-1.4.jar;%MyHomeDir%\.m2\repository\org\apache\maven\doxia\doxia-module-xhtml\1.4\doxia-module-xhtml-1.4.jar;%MyHomeDir%\.m2\repository\org\apache\maven\doxia\doxia-module-fml\1.4\doxia-module-fml-1.4.jar;%MyHomeDir%\.m2\repository\org\codehaus\plexus\plexus-i18n\1.0-beta-7\plexus-i18n-1.0-beta-7.jar;%MyHomeDir%\.m2\repository\org\codehaus\plexus\plexus-velocity\1.1.7\plexus-velocity-1.1.7.jar;%MyHomeDir%\.m2\repository\org\apache\velocity\velocity\1.5\velocity-1.5.jar;%MyHomeDir%\.m2\repository\org\apache\velocity\velocity-tools\2.0\velocity-tools-2.0.jar;%MyHomeDir%\.m2\repository\commons-chain\commons-chain\1.1\commons-chain-1.1.jar;%MyHomeDir%\.m2\repository\sslext\sslext\1.2-0\sslext-1.2-0.jar;%MyHomeDir%\.m2\repository\org\apache\struts\struts-core\1.3.8\struts-core-1.3.8.jar;%MyHomeDir%\.m2\repository\antlr\antlr\2.7.2\antlr-2.7.2.jar;%MyHomeDir%\.m2\repository\org\apache\struts\struts-taglib\1.3.8\struts-taglib-1.3.8.jar;%MyHomeDir%\.m2\repository\org\apache\struts\struts-tiles\1.3.8\struts-tiles-1.3.8.jar;%MyHomeDir%\.m2\repository\commons-collections\commons-collections\3.2.1\commons-collections-3.2.1.jar;%MyHomeDir%\.m2\repository\org\apache\maven\shared\maven-doxia-tools\1.2.1\maven-doxia-tools-1.2.1.jar;%MyHomeDir%\.m2\repository\commons-io\commons-io\1.4\commons-io-1.4.jar;%MyHomeDir%\.m2\repository\org\apache\maven\maven-artifact-manager\2.0.6\maven-artifact-manager-2.0.6.jar;%MyHomeDir%\.m2\repository\org\apache\maven\maven-repository-metadata\2.0.6\maven-repository-metadata-2.0.6.jar;%MyHomeDir%\.m2\repository\org\apache\maven\maven-model\2.0.6\maven-model-2.0.6.jar;%MyHomeDir%\.m2\repository\org\codehaus\plexus\plexus-container-default\1.0-alpha-9\plexus-container-default-1.0-alpha-9.jar;%MyHomeDir%\.m2\repository\classworlds\classworlds\1.1-alpha-2\classworlds-1.1-alpha-2.jar;%MyHomeDir%\.m2\repository\org\codehaus\plexus\plexus-resources\1.0-alpha-7\plexus-resources-1.0-alpha-7.jar;%MyHomeDir%\.m2\repository\org\codehaus\plexus\plexus-utils\1.5.6\plexus-utils-1.5.6.jar;%MyHomeDir%\.m2\repository\org\sonatype\plexus\plexus-build-api\0.0.7\plexus-build-api-0.0.7.jar;%MyHomeDir%\.m2\repository\commons-net\commons-net\3.3\commons-net-3.3.jar;%MyHomeDir%\.m2\repository\p2\osgi\bundle\com.sap.hana.dp.adapterframework\1.2.5\com.sap.hana.dp.adapterframework-1.2.5.jar;%MyHomeDir%\.m2\repository\p2\osgi\bundle\com.google.gson\2.1.0.v201203072145\com.google.gson-2.1.0.v201203072145.jar;%MyHomeDir%\.m2\repository\p2\osgi\bundle\org.antlr.runtime\3.2.0.v201101311130\org.antlr.runtime-3.2.0.v201101311130.jar;%MyHomeDir%\.m2\repository\p2\osgi\bundle\org.apache.log4j\1.2.15.v201012070815\org.apache.log4j-1.2.15.v201012070815.jar;%MyHomeDir%\.m2\repository\p2\osgi\bundle\org.eclipse.osgi\3.9.1.v20140110-1610\org.eclipse.osgi-3.9.1.v20140110-1610.jar;%MyProjectDir%\lib\commons-net.jar%MyProjectDir%\lib\commons-net.jar
[DEBUG] File Encoding is UTF-8

So why is the Plugin Adding the libary commons-net.jar TWICE to the AuxClasspath and due to that scrambles the AuxClasspath by not putting a comma between the 2 entries which results in the jar is not found on the classpath.

**Comment by gleclaire** [comment] 2017-07-28 19:59
fixed with PR 57.  Duplicate of issue 55

**Closed by gleclaire** 2017-07-28 19:59 UTC
